name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    container: ryuichiueda/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
    steps:
      - uses: actions/checkout@v2    #コンテナのカレントディレクトリにリポジトリを配置
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/    # リポジトリの下をros2_ws下にコピー
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/talk_listen_test.bash /root
